{% set name = "opbeat" %}
{% set version = "3.6.1" %}
{% set sha256 = "bd03103d56b53b85d097f01ba72b44c65d2607fcf67f17590878f57fc616eb21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python <3.7
    - pip
  run:
    - python <3.7
    - django >=1.8
    - urllib3
    - certifi

about:
  home: https://github.com/opbeat/opbeat_python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python agent for Opbeat.'
  description: |
    It provides full out-of-the-box support for many of the popular frameworks, including Django, 
    and Flask. Opbeat also includes drop-in support for any WSGI-compatible web application.
    Your application doesn't live on the web? No problem! Opbeat is easy to use in any Python application.
  doc_url: https://opbeat.com/docs/topics/python/
  dev_url: https://github.com/opbeat/opbeat_python

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
