travis:
  secure:
    BINSTAR_TOKEN: DVEl1+m4plQGTWBCXvN4H7FZ78QMkEE/IoTeZNOvHhskYmqBd4co14id+wxs/Sgdl8A3oBl7AkLN3VmDhN5Rk6W7rpbac0Enn6rIkbXE3oumiX0k+kWJ4ooFJDSBek4hE93Q9Kk/MZ8c1ndtTQ+C0s+86aX60Ccczn/18cYZ93Zw6qG0Cr6QWjL1Z03y5AC9tx3ESNn6i00I0Ihb7+nN9ICEV4zlae9xdTI/Jo6qtG1YaVxfcp3b/P6TfHP67HHFVJyvU0sZpJqxtRVch+5vZDgs+eyJnfNGNjilH2YmRg75xTV6epaQahHTz/QXn2mwv96OC7gYqYQEAQaVicBDYtDbaLjeDqBY9HAR7RsLApfrR5UtWU4IpPtM1FL/KjrgebkLsxVaSzc8exiICO6158Ax3OfJXoHYYEOrseECBk2uQ7c2RKWoOu9n0jfqTjHGSIdkp0odu4wFHhed3wFjzoQw8Q/Msn/8QkOyPm31vujsWhWD2tnKmpF+FL3Wj5E+MOOCO2wwo22jyKsTnCQpzMUJuoU3LCDLZghNX/bOYk3OvdZJcxrX/2jXMh2bzvr8xzfle7xlSVWmaZTNRa2enq5PgKisA+hP7FmHQ7znJ+BRoNRmh5HVhqgXrBLYfCBq+xfmpsGTdGwbSAcvAll9o5VLFBkIAk8KrazYyaemQEE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
